from __future__ import annotations

import numpy as np
import pandas as pd


def _commission(amount: float, fee_rate: float, min_commission: float) -> float:
    if amount <= 0:
        return 0.0
    return max(amount * fee_rate, min_commission)


def _is_a_share_limit_blocked(row: pd.Series, side: str, limit_rate: float) -> bool:
    """Approximate A-share limit-up/limit-down trading block.

    side='buy': cannot buy if the open is already near limit-up.
    side='sell': cannot sell if the open is already near limit-down.
    This is an approximation for daily data because真实逐笔/盘口数据不可见。
    """
    prev_close = row.get("Prev_Close", np.nan)
    open_price = row.get("Open", np.nan)
    if pd.isna(prev_close) or pd.isna(open_price) or prev_close <= 0:
        return False
    if side == "buy":
        return open_price >= prev_close * (1 + limit_rate) * 0.999
    if side == "sell":
        return open_price <= prev_close * (1 - limit_rate) * 1.001
    return False


def run_backtest(
    df: pd.DataFrame,
    initial_cash: float = 100000.0,
    fee_rate: float = 0.0003,
    slippage_rate: float = 0.0002,
    sell_tax_rate: float = 0.0005,
    lot_size: int = 100,
    min_commission: float = 5.0,
    trade_price_col: str = "Open",
    enable_t1: bool = True,
    enable_limit_filter: bool = True,
    limit_rate: float = 0.10,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Sequential long-only backtest for A-share style trading.

    Required columns: Open, High, Low, Close, Volume, Position.
    Position is the target position generated by strategy, normally shifted by 1 day.

    Main realistic rules:
    - 100-share round lot buying by default.
    - Commission with minimum commission.
    - Slippage on both buy and sell.
    - Stamp duty / sell tax on sell side.
    - T+1 sell restriction approximation.
    - Limit-up / limit-down and suspended-day approximation using daily data.
    """
    if "Position" not in df.columns:
        raise ValueError("Backtest input must contain a Position column.")
    for col in ["Open", "High", "Low", "Close", "Volume"]:
        if col not in df.columns:
            raise ValueError(f"Backtest input missing required column: {col}")
    if trade_price_col not in df.columns:
        raise ValueError(f"trade_price_col={trade_price_col} not found in dataframe.")

    out = df.copy().sort_index()
    out["Target_Position"] = out["Position"].fillna(0).clip(0, 1)
    out["Prev_Close"] = out["Close"].shift(1)

    cash = float(initial_cash)
    shares = 0
    entry_date = None
    entry_price = 0.0
    entry_cost = 0.0
    entry_shares = 0
    last_buy_date = None

    daily_rows = []
    trade_rows = []

    for dt, row in out.iterrows():
        target = int(row["Target_Position"] > 0)
        raw_price = float(row[trade_price_col])
        close_price = float(row["Close"])
        volume = float(row.get("Volume", 0) or 0)
        suspended = bool(volume <= 0 or pd.isna(raw_price) or raw_price <= 0)

        action = "HOLD"
        reason = ""
        trade_value = 0.0
        commission = 0.0
        tax = 0.0
        slippage_cost = 0.0
        realized_pnl = 0.0

        # Sell first if target becomes 0.
        if shares > 0 and target == 0:
            if suspended:
                reason = "停牌/无成交量，无法卖出"
            elif enable_t1 and last_buy_date is not None and dt == last_buy_date:
                reason = "T+1限制，当日买入不可卖出"
            elif enable_limit_filter and _is_a_share_limit_blocked(row, "sell", limit_rate):
                reason = "疑似跌停，无法卖出"
            else:
                exec_price = raw_price * (1 - slippage_rate)
                trade_value = shares * exec_price
                commission = _commission(trade_value, fee_rate, min_commission)
                tax = trade_value * sell_tax_rate
                slippage_cost = shares * raw_price * slippage_rate
                cash += trade_value - commission - tax
                realized_pnl = cash - entry_cost
                action = "SELL"
                reason = "策略卖出"
                trade_rows.append({
                    "Entry Date": entry_date,
                    "Entry Price": entry_price,
                    "Exit Date": dt,
                    "Exit Price": exec_price,
                    "Shares": shares,
                    "Buy Cost": entry_cost,
                    "Sell Value After Cost": cash,
                    "PnL": realized_pnl,
                    "Return": realized_pnl / entry_cost if entry_cost else 0.0,
                    "Holding Days": (dt - entry_date).days if entry_date is not None else 0,
                    "Sell Commission": commission,
                    "Sell Tax": tax,
                })
                shares = 0
                entry_date = None
                entry_price = 0.0
                entry_cost = 0.0
                entry_shares = 0

        # Buy if target is 1 and we are flat.
        if shares == 0 and target == 1:
            if suspended:
                reason = "停牌/无成交量，无法买入"
            elif enable_limit_filter and _is_a_share_limit_blocked(row, "buy", limit_rate):
                reason = "疑似涨停，无法买入"
            else:
                exec_price = raw_price * (1 + slippage_rate)
                # estimate one lot total cost including commission; then buy max affordable round lots
                per_share_total = exec_price * (1 + fee_rate)
                max_shares = int(cash // (per_share_total * lot_size)) * lot_size if lot_size > 1 else int(cash // per_share_total)
                if max_shares <= 0:
                    reason = "资金不足，无法买入一手"
                else:
                    gross = max_shares * exec_price
                    commission = _commission(gross, fee_rate, min_commission)
                    # if min commission pushes over cash, reduce by lot until affordable
                    while max_shares > 0 and gross + commission > cash:
                        max_shares -= lot_size
                        gross = max_shares * exec_price
                        commission = _commission(gross, fee_rate, min_commission)
                    if max_shares <= 0:
                        reason = "资金不足，无法覆盖最小佣金"
                    else:
                        shares = max_shares
                        trade_value = gross
                        slippage_cost = max_shares * raw_price * slippage_rate
                        cash -= gross + commission
                        entry_date = dt
                        entry_price = exec_price
                        entry_cost = gross + commission
                        entry_shares = shares
                        last_buy_date = dt
                        action = "BUY"
                        reason = "策略买入"

        market_value = shares * close_price
        equity = cash + market_value
        daily_rows.append({
            "Date": dt,
            "Cash": cash,
            "Shares": shares,
            "Market_Value": market_value,
            "Equity": equity,
            "Actual_Position": 1 if shares > 0 else 0,
            "Action": action,
            "Reason": reason,
            "Trade_Value": trade_value,
            "Commission": commission,
            "Sell_Tax": tax,
            "Slippage_Cost": slippage_cost,
            "Realized_PnL": realized_pnl,
        })

    daily = pd.DataFrame(daily_rows).set_index("Date")
    out = out.join(daily, how="left")
    out["Strategy_Return"] = out["Equity"].pct_change().fillna(0)
    out["Market_Return"] = out["Close"].pct_change().fillna(0)
    out["BuyHold_Equity"] = initial_cash * (1 + out["Market_Return"]).cumprod()
    out["Drawdown"] = out["Equity"] / out["Equity"].cummax() - 1
    out["Trade"] = out["Action"].map({"BUY": 1, "SELL": -1}).fillna(0).astype(int)

    trades = pd.DataFrame(trade_rows)
    metrics = calculate_metrics(out, trades, initial_cash)
    return out, trades, metrics


def calculate_metrics(df: pd.DataFrame, trades: pd.DataFrame, initial_cash: float) -> dict:
    if df.empty:
        return {}

    final_equity = float(df["Equity"].iloc[-1])
    total_return = final_equity / initial_cash - 1
    market_total_return = float(df["BuyHold_Equity"].iloc[-1] / initial_cash - 1)
    max_drawdown = float(df["Drawdown"].min())

    daily_ret = df["Strategy_Return"].dropna()
    sharpe = 0.0 if daily_ret.std() == 0 or np.isnan(daily_ret.std()) else float(np.sqrt(252) * daily_ret.mean() / daily_ret.std())
    annual_return = float((1 + total_return) ** (252 / max(len(df), 1)) - 1) if total_return > -1 else -1.0

    exposure = float((df["Actual_Position"] > 0).mean()) if "Actual_Position" in df.columns else 0.0
    total_commission = float(df.get("Commission", pd.Series(dtype=float)).sum())
    total_tax = float(df.get("Sell_Tax", pd.Series(dtype=float)).sum())
    total_slippage = float(df.get("Slippage_Cost", pd.Series(dtype=float)).sum())

    if trades.empty:
        win_rate = 0.0
        avg_trade_return = 0.0
        trade_count = 0
        profit_factor = 0.0
        avg_holding_days = 0.0
        best_trade = 0.0
        worst_trade = 0.0
    else:
        pnl = trades["PnL"].astype(float)
        wins = pnl[pnl > 0].sum()
        losses = -pnl[pnl < 0].sum()
        win_rate = float((trades["Return"] > 0).mean())
        avg_trade_return = float(trades["Return"].mean())
        trade_count = int(len(trades))
        profit_factor = float(wins / losses) if losses > 0 else (float("inf") if wins > 0 else 0.0)
        avg_holding_days = float(trades["Holding Days"].mean())
        best_trade = float(trades["Return"].max())
        worst_trade = float(trades["Return"].min())

    return {
        "Final Equity": final_equity,
        "Total Return": float(total_return),
        "Annual Return": annual_return,
        "Buy & Hold Return": market_total_return,
        "Max Drawdown": max_drawdown,
        "Sharpe Ratio": sharpe,
        "Win Rate": win_rate,
        "Average Trade Return": avg_trade_return,
        "Trade Count": trade_count,
        "Profit Factor": profit_factor,
        "Average Holding Days": avg_holding_days,
        "Best Trade": best_trade,
        "Worst Trade": worst_trade,
        "Exposure": exposure,
        "Total Commission": total_commission,
        "Total Sell Tax": total_tax,
        "Total Slippage": total_slippage,
        "Total Cost": total_commission + total_tax + total_slippage,
    }
